[package]
name = "eee-hyst"
version = "0.3.0"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]

[dependencies]

[dependencies.clap]
version = "2.29" 
default-features = true
features = ["yaml"]
