[package]
name = "eee-hyst"
version = "0.6.3"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2021"
description = "A Rustified Simulator for 10Gb/s EEE with Configurable Hysteresis"

[dependencies.clap]

version = "4.4.8"
features = ["derive", "wrap_help"]
