[package]
name = "eee-hyst"
version = "0.5.0"
authors = ["Miguel Rodríguez Pérez <miguel@det.uvigo.gal>"]
edition = "2018"

[dependencies]

[dependencies.clap]
version = "2.32" 
default-features = true
features = ["yaml"]
